TRAINING_SET = ["William_Madison", "Algernon_Edward_Sartoris", "James_Southall_Wilson", "William_Alfred_Packard",
                "Hancock_Lee", "Joseph_Stanley_Brown", "Asa_Waters", "Calvin_Galusha_Coolidge", "Thomas_Gardner_Ford",
                "Robert_T._Gannett", "Thomas_Boylston", "Bartholomew_Dandridge",
                "Robert_Tyler_(Confederate_Register_of_the_Treasury)", "Carter_Henry_Harrison_I", "Grace_Roosevelt",
                "Edward_L._Hall", "Ellen_Roosevelt", "Lawrence_Augustine_Washington", "Valentine_Hall", "Elihu_Adams",
                "Joseph_Wilson_Baines", "Jenna_Welch", "Clifton_Daniel", "Bobby_Koch", "Thomas_J._Preston_Jr.",
                "Augustine_Washington_Jr.", "Benjamin_Harrison_III", "Clifton_Truman_Daniel", "Hannah_Van_Buren",
                "Elizabeth_Harrison_Walker", "Marion_O_Shea_Roosevelt", "Ronald_A._Wilford", "James_Beverly_Langford",
                "John_Augustine_Washington", "Allan_Hoover", "Selwa_Roosevelt", "George_Herbert_Walker_Jr.",
                "Grace_Roosevelt_McMillan", "John_Witherspoon_Scott", "Charles_Washington", "Sarah_Lincoln_Grigsby",
                "Samuel_Polk", "Jerome_B._Chaffee", "Samuel_Ealy_Johnson_Sr.", "Scott_Willits", "Seth_Taft",
                "Mary_Abigail_Fillmore", "Donald_A._Nixon", "Joseph_Ball_(Virginia_public_servant)",
                "Francis_Cleveland", "Susan_Roosevelt_Weld", "Alpheus_Spring_Packard",
                "Carter_Bassett_Harrison_(1811–1839)", "Caroline_C._Fillmore", "Joe_Ellis",
                "Thomas_Bolling_Robertson", "Jane_Irwin_Harrison", "Horace_Dutton_Taft", "Joseph_Edward_Willard",
                "Edgar_N._Eisenhower", "Henry_Honoré", "Tricia_Nixon_Cox", "Dorothy_Walker_Bush",
                "Mary_Benedict_Cushing", "Isaac_Roosevelt_(businessman)", "Hannah_Milhous_Nixon",
                "Millard_Powers_Fillmore", "James_E._Robinson", "George_C._Adams",
                "Thomas_Boylston_Adams_(1772–1832)", "Ruth_Carter_Stapleton", "James_I._Van_Alen",
                "James_A._Roosevelt", "Jesse_Root_Grant_(politician)", "Charles_T._Payne",
                "Daniel_Stewart_(Brigadier_General)", "Donald_Nixon", "Joseph_Willard_Roosevelt",
                "Edith_Derby_Williams", "John_Alexander_Tyler", "Ethel_du_Pont", "Ruth_Cleveland",
                "Hilborne_Roosevelt", "George_Washington_Baines", "Anne_Eisenhower", "Charles_Adams_(1770–1800)",
                "Thomas_Lincoln,_Jr.", "Jennie_Eisenhower", "Alexander_Ellis_III", "James_Roosevelt_Roosevelt",
                "Susanna_Boylston", "Mamie_Lincoln_Isham", "Eleanor_Roosevelt_Seagraves", "Sharon_Bush",
                "William_S._Cowles", "Christopher_Nixon_Cox", "David_Davis_Walker", "John_Amen", "Abram_Garfield",
                "Alvin_Saunders",
                "William_H._T._Bush", "Lawrence_Lewis_(1767–1839)", "Mary_Dimmick_Harrison", "Emlen_Roosevelt",
                "Ulysses_S._Grant_IV", "George_Read_III", "Marvin_Bush", "Andrea_Catsimatidis", "Hulbert_Taft",
                "Louise_Taft", "Frederick_Tracy_Dent", "M._R._D._Foot", "John_Custis", "Joseph_Pannell_Taylor",
                "Rutherford_P._Hayes", "John_Dandridge", "Mildred_Gale", "Frederic_Adrian_Delano",
                "David_Gardiner_Tyler", "Steven_Ford", "Brooks_Adams", "Edward_John_Sartoris",
                "Eleanor_Butler_Roosevelt", "Esther_Cleveland", "James_Jacobus_Roosevelt", "Earl_D._Eisenhower",
                "Adelaide_Kemble", "Albert_Bosanquet", "Zachary_Taylor_Wood", "Chapman_Grant",
                "Angelica_Singleton_Van_Buren", "Letitia_Christian_Tyler", "Dorothy_Bush_Koch",
                "William_Howard_Taft_III", "George_Herbert_Walker_III", "Mary_Harrison_McKee",
                "Lawrence_Washington_(1659–1698)", "John_Ellis_Roosevelt", "Edward_Nixon", "James_Stephens_Bulloch",
                "Tadd_Roosevelt", "Clara_Longworth_de_Chambrun", "Alpheus_Spring_Packard_Sr.", "Benjamin_Harrison_IV",
                "David_Lauren", "Benjamin_Pierce_(governor)", "Stewart_Alsop", "James_Roosevelt_(lawyer)",
                "Dorothy_Ayer_Gardner_Ford", "Marvin_Pierce", "Helen_Taft_Manning", "Nancy_Walker_Bush_Ellis",
                "Letitia_Semple", "Mary_Lincoln_Beckwith", "Eleanor_Parke_Custis_Lewis", "Auma_Obama",
                "Quentin_Roosevelt_II", "Martha_Parke_Custis_Peter", "Jesse_Appleton", "Ela_Collins",
                "John_Tyler_Sr.",
                "James_Roosevelt_(1760–1847)", "James_Madison_Sr.", "Robert_Taft_Jr.", "Sara_Wilford",
                "George_Washington_Adams", "Mary_Lincoln_Crume", "Peter_Rawson_Taft", "John_Adams_II", "Malik_Obama",
                "Marian_Shields_Robinson", "Granville_Roland_Fortescue", "Cornelius_V._S._Roosevelt",
                "Peter_Chardon_Brooks", "Ida_Stover_Eisenhower", "Carter_Bassett_Harrison", "Sam_Houston_Johnson",
                "James_I._Roosevelt", "John_Coolidge", "Lucy_Hayes_Herron", "Ulysses_S._Grant_Jr.",
                "John_H._Trumbull",
                "Mary_Elizabeth_Bliss", "Zabdiel_Boylston", "Abraham_Van_Buren_(I)", "Elizabeth_Ann_Blaesing",
                "Theodore_Roosevelt_IV", "Eleanor_Calvert", "Fielding_Lewis", "Robert_Carter_I", "Jonathan_S._Bush",
                "John_M._Walker", "Edward_Baker_Lincoln", "Richard_Taylor_(colonel)", "John_Scott_Harrison",
                "John_Prescott_Ellis", "Theodore_Roosevelt_III", "John_Payne_Todd", "Jonathan_Bush",
                "Martha_Ellen_Young_Truman", "Lynda_Bird_Johnson_Robb", "Leigh_McCullough", "Augustine_Warner_Jr.",
                "Russell_Benjamin_Harrison", "Samuel_Washington", "Cornelius_Roosevelt", "Charles_Henry_King",
                "Samuel_P._Bush", "Nan_Britton", "Jessie_Harlan_Lincoln", "Harry_Augustus_Garfield",
                "John_Quincy_Adams_II", "Anna_Hall_Roosevelt", "Mary_Harlan_Lincoln", "Augustine_Washington",
                "Gerald_Rudolff_Ford", "Webb_Hayes", "Corinne_Alsop_Cole", "Luci_Baines_Johnson",
                "James_Rudolph_Garfield", "John_Calvin_Coolidge_Sr.", "Margaret_Hoover", "Jack_Carter_(politician)",
                "Frances_Cleveland", "David_Gardiner_(politician)", "William_Cranch", "John_Cleves_Symmes",
                "Anthony_di_Bonaventura", "Charles_Phelps_Taft_II", "David_Frederick_Wallace",
                "Alexander_McCormick_Sturm", "Ida_Marie_Honoré", "Ambrose_Madison", "Richard_Falley_Cleveland",
                "John_Roosevelt_Boettiger", "Franklin_Delano_Roosevelt_III", "Marshall_Eugene_DeWolfe",
                "Betty_Washington_Lewis", "Daniel_Parke_Custis", "George_Steptoe_Washington",
                "Frances_Jones_(colonist)", "Bushrod_Washington", "Mary_Ball_Washington", "William_Fairfax",
                "Craig_Robinson_(basketball)", "Lawrence_Washington_(1718–1752)", "Zachary_Taylor",
                "William_Henry_Harrison", "Michelle_Obama", "Calvin_Coolidge", "Benjamin_Harrison",
                "Rutherford_B._Hayes", "Grover_Cleveland", "Millard_Fillmore", "Martin_Van_Buren", "Herbert_Hoover",
                "John_Quincy_Adams", "George_H._W._Bush", "Franklin_Pierce", "Gerald_Ford", "John_Tyler",
                "James_A._Garfield", "James_Madison", "Harry_S._Truman", "Abraham_Lincoln", "William_Howard_Taft",
                "Barack_Obama", "Richard_Nixon", "George_W._Bush", "Warren_G._Harding", "James_K._Polk",
                "Franklin_D._Roosevelt", "Jimmy_Carter", "George_Washington", "Dwight_D._Eisenhower", "John_Adams",
                "Theodore_Roosevelt", "Ulysses_S._Grant", "Lyndon_B._Johnson"]

TEST_SET = ["Dabney_S._Carr", "Maxwell_Karger", "Lyncoya_Jackson", "William_McKinley_Sr.",
            "Eleanor_Wilson_McAdoo", "Lady_Elizabeth_Cavendish", "James_Wilson_(journalist)",
            "Tatiana_Schlossberg", "John_Randolph_(politician)", "Jack_Reagan", "Francis_Bowes_Sayre_Jr.",
            "George_Skakel", "Morrison_Foster", "Edward_B._Cassatt", "William_Randolph_II", "Roger_Clinton_Sr.",
            "Tina_Onassis_Niarchos", "Stanislaw_Albrecht_Radziwill", "George_Hay_(Virginia_judge)",
            "Margaret_Woodrow_Wilson", "Kyra_Kennedy", "Edward_Francis_Blewitt", "Edward_Randolph",
            "William_Barclay_Foster", "Lara_Trump", "David_Sills", "Virginia_Randolph_Cary", "Vanessa_Trump",
            "Lady_Anne_Tree", "Stephen_Edward_Smith", "John_Donelson", "Francis_Bowes_Sayre_Sr.", "Blaine_Trump",
            "Lucy_Jefferson_Lewis", "Neil_Reagan", "James_Pleasants", "Edwin_Schlossberg",
            "Eliza_McCardle_Johnson", "David_T._Patterson", "Jeff_Dwire", "Douglas_Harriman_Kennedy",
            "Janet_Lee_Bouvier", "Anthony_Radziwill", "Patrick_Schwarzenegger",
            "Joseph_Jones_(Virginia_politician)", "Peter_Carr_(Virginia_politician)", "Richard_Randolph",
            "Virginia_Clinton_Kelley", "Joseph_Ruggles_Wilson", "Thomas_Randolph_of_Tuckahoe",
            "Janet_Auchincloss_Rutherfurd", "Mary_Cavendish,_Duchess_of_Devonshire", "Eliza_Monroe_Hay",
            "Sydney_Turing_Barlow_Lawford", "Martha_Johnson_Patterson", "Marc_Mezvinsky", "Rose_Schlossberg",
            "Katherine_Schwarzenegger", "Mary_Arthur_McElroy", "Neilia_Hunter_Biden",
            "James_Monroe_(New_York_politician)", "Eliza_Clayland_Tomlinson_Foster",
            "William_Cavendish,_Marquess_of_Hartington", "Isham_Randolph_of_Dungeness", "Maureen_Reagan",
            "Dabney_Carr", "Jessie_Woodrow_Wilson_Sayre", "John_Wayles_Eppes", "Nelle_Wilson_Reagan",
            "Jacob_Johnson_(father_of_Andrew_Johnson)", "Patricia_Kennedy_Lawford", "Mary_Richardson_Kennedy",
            "David_A._Kennedy", "Tiffany_Trump", "Michael_LeMoyne_Kennedy", "Edith_Ewing_Bouvier_Beale",
            "Elizabeth_Christ_Trump", "Daniel_Smith_Donelson", "Gavin_Arthur", "Michael_Temple_Canfield",
            "Roger_Clinton_Jr.", "Hugh_D._Auchincloss", "Ellen_Axson_Wilson", "James_Buchanan",
            "Chester_A._Arthur", "James_Monroe", "Joe_Biden", "William_McKinley", "Woodrow_Wilson",
            "Bill_Clinton", "Andrew_Johnson", "Thomas_Jefferson", "Ronald_Reagan", "Andrew_Jackson",
            "Donald_Trump", "John_F._Kennedy"]